[package]
name = "aster-framevm-pci"
version = "0.1.0"
edition.workspace = true

[dependencies]
align_ext.workspace = true
bitflags.workspace = true
component.workspace = true
int-to-c-enum.workspace = true
ostd = { path = "../../../../kernel/comps/framevisor-ostd", package = "aster-framevisor-ostd" }
spin.workspace = true

[lints]
workspace = true
