#!/bin/sh

# SPDX-License-Identifier: MPL-2.0

set -e

GUEST_CID="${FRAMEV_VSOCK_GUEST_CID:-3}"
GUEST_PORT="${FRAMEV_VSOCK_GUEST_PORT:-4321}"
GUEST_CLOSED_PORT="${FRAMEV_VSOCK_GUEST_CLOSED_PORT:-65531}"
SMALL_PAYLOAD="${FRAMEV_VSOCK_SMALL_PAYLOAD:-4096}"
LARGE_PAYLOAD="${FRAMEV_VSOCK_LARGE_PAYLOAD:-131072}"
BIN="${FRAMEV_VSOCK_HOST_BIN:-./framev_vsock_echo}"

"${BIN}" client "${GUEST_CID}" "${GUEST_PORT}" "${SMALL_PAYLOAD}" shutdown
"${BIN}" client "${GUEST_CID}" "${GUEST_PORT}" "${LARGE_PAYLOAD}" shutdown
"${BIN}" expect-fail "${GUEST_CID}" "${GUEST_CLOSED_PORT}"
