[package]
name = "aster-framevm-softirq"
version = "0.1.0"
edition.workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
aster-util = { workspace = true, default-features = false }
component.workspace = true
intrusive-collections.workspace = true
ostd = { path = "../../../../kernel/comps/framevisor-ostd", package = "aster-framevisor-ostd" }
spin.workspace = true

[lints]
workspace = true
