[package]
name = "aster-framevm-bigtcp"
version = "0.1.0"
edition.workspace = true

[dependencies]
aster-softirq = { path = "../softirq", package = "aster-framevm-softirq" }
aster-util = { package = "aster-framevisor-util", path = "../../../../kernel/comps/framevisor-ostd/libs/aster-util", default-features = false }
bitflags.workspace = true
int-to-c-enum.workspace = true
jhash.workspace = true
ostd = { path = "../../../../kernel/comps/framevisor-ostd", package = "aster-framevisor-ostd" }
smoltcp.workspace = true
spin.workspace = true
takeable.workspace = true

[lints]
workspace = true
