// SPDX-License-Identifier: MPL-2.0

//! Minimal device helpers used by copied syscall handlers.

use ostd::sync::{Once, SpinLock};
use rand::{RngCore, SeedableRng, rngs::StdRng};

use crate::prelude::*;

static RNG: Once<SpinLock<StdRng>> = Once::new();

/// Initializes device helpers used by copied syscall handlers.
pub fn init() {
    let seed = get_random_seed();
    RNG.call_once(|| SpinLock::new(StdRng::from_seed(seed)));
}

/// Fills a user writer with random bytes.
pub fn geturandom(writer: &mut VmWriter<'_>) -> Result<usize> {
    const IO_CAPABILITY: usize = 4096;

    if !writer.has_avail() {
        return Ok(0);
    }

    let mut buffer = vec![0; writer.avail().min(IO_CAPABILITY)];
    let mut written_bytes = 0;

    while writer.has_avail() {
        let write_len = writer.avail().min(IO_CAPABILITY);
        getrandom_bytes(&mut buffer[..write_len]);
        match writer.write_fallible(&mut VmReader::from(&buffer[..write_len])) {
            Ok(len) => written_bytes += len,
            Err((err, 0)) if written_bytes == 0 => return Err(err.into()),
            Err((_, len)) => return Ok(written_bytes + len),
        }
    }

    Ok(written_bytes)
}

/// Fills a user writer with random bytes.
pub use geturandom as getrandom;

/// Fills `dst` with random bytes from the kernel RNG.
///
/// It is cryptographically secure when initialized from the hardware RNG, as
/// documented in [`rand::rngs::StdRng`]. The timestamp fallback matches the
/// current kernel fallback and is intentionally logged as insecure.
pub fn getrandom_bytes(dst: &mut [u8]) {
    RNG.get()
        .expect("kernel device RNG must be initialized before use")
        .lock()
        .fill_bytes(dst);
}

fn get_random_seed() -> <StdRng as SeedableRng>::Seed {
    if let Some(seed) = read_seed_from_hardware() {
        ostd::info!("use randomness generated by hardware");
        return seed;
    }

    // TODO: Collect entropy from environment noise for better security.
    ostd::warn!("use randomness based on the timestamp, which is insecure");
    read_seed_from_timestamp()
}

fn read_seed_from_hardware() -> Option<<StdRng as SeedableRng>::Seed> {
    read_seed_from(ostd::arch::read_random)
}

fn read_seed_from_timestamp() -> <StdRng as SeedableRng>::Seed {
    read_seed_from(|| Some(ostd::arch::read_tsc())).expect("TSC seed source always returns a value")
}

fn read_seed_from(
    mut next_random: impl FnMut() -> Option<u64>,
) -> Option<<StdRng as SeedableRng>::Seed> {
    let mut seed = <StdRng as SeedableRng>::Seed::default();

    let mut chunks = seed.as_mut().chunks_exact_mut(size_of::<u64>());
    for chunk in chunks.by_ref() {
        let value = next_random()?;
        chunk.copy_from_slice(&value.to_ne_bytes());
    }

    let tail = chunks.into_remainder();
    if !tail.is_empty() {
        let value = next_random()?;
        tail.copy_from_slice(&value.to_ne_bytes()[..tail.len()]);
    }

    Some(seed)
}
