// SPDX-License-Identifier: MPL-2.0

//! Provides ASCII art representations of Asterinas project logos.
//!
//! This crate offers two static string slices containing the logo:
//! a classic black-and-white version and
//! a vibrant, gradient-colored one,
//! suitable for splash screens or command-line tool branding.

#![no_std]

/// Returns the ASCII art of the Asterinas logo in black and white.
///
/// ## Generation
///
/// The ASCII art was generated using the online tool at
/// [asciiart.eu](https://www.asciiart.eu/image-to-ascii).
pub fn get_black_white_version() -> &'static str {
    // The ASCII art is generated using an online tool:
    // https://www.asciiart.eu/image-to-ascii
    static LOGO_ASCII_ART: &str = include_str!("logo_ascii_art.txt");
    LOGO_ASCII_ART
}

/// Returns the ASCII art of the Asterinas logo with gradient colors.
///
/// The colors are represented using ANSI escape codes,
/// so this version must be viewed in a terminal.
///
/// ## Generation
///
/// This version is generated by the CLI version of this crate.
/// To regenerate it, run the following command:
///
/// ```sh
/// cd logo-ascii-art/
/// cargo run --features=color > src/logo_ascii_art_gradient.txt
/// ```
pub fn get_gradient_color_version() -> &'static str {
    // The gradient color version is generated by running:
    // ```
    // cd logo_ascii_art && cargo run > src/logo_ascii_art_gradient.txt
    // ```
    static LOGO_ASCII_ART: &str = include_str!("logo_ascii_art_gradient.txt");
    LOGO_ASCII_ART
}

/// Returns the ASCII art of the FrameVM logo.
pub fn get_framevm_gradient_color_version() -> &'static str {
    r#"  ______                         __      ____  __
 |  ____|                        \ \    / /  \/  |
 | |__ _ __ __ _ _ __ ___   ___   \ \  / /| \  / |
 |  __| '__/ _` | '_ ` _ \ / _ \   \ \/ / | |\/| |
 | |  | | | (_| | | | | | |  __/    \  /  | |  | |
 |_|  |_|  \__,_|_| |_| |_|\___|     \/   |_|  |_|

        FrameVM
        Released under Mozilla Public License v2.0"#
}
