#!/usr/bin/env python3
# SPDX-License-Identifier: MPL-2.0

"""Generates FrameVM syscall metadata from the kernel syscall table."""

from __future__ import annotations

import argparse
import difflib
import re
import sys
from dataclasses import dataclass
from pathlib import Path


ENTRY_RE = re.compile(r"^\s*(SYS_[A-Z0-9_]+)\s*=\s*(\d+)\s*=>\s*(.*?)\s*;\s*$")
STANDALONE_CONST_RE = re.compile(r"^\s*pub\s+const\s+(SYS_[A-Z0-9_]+)\s*:\s*u64\s*=\s*(\d+)\s*;\s*$")
GENERATED_HEADER = """// SPDX-License-Identifier: MPL-2.0
//
// @generated by tools/generate_framevm_syscall_metadata.py
// Source of truth: kernel/src/syscall/arch/x86.rs
// Service dispatch source: services/aster-framevm/src/syscall/arch/x86.rs
// Generation command:
//   python3 tools/generate_framevm_syscall_metadata.py
//
// Do not edit by hand. Run the generation command instead.
"""
FRAMEVM_ONLY_UNSUPPORTED_SYSCALLS = {
    "SYS_RSEQ": "FrameVM keeps this Linux x86-64 number as an explicit ENOSYS entry; the main kernel has no rseq syscall handler.",
}


@dataclass(frozen=True)
class SyscallEntry:
    name: str
    number: int
    handler: str


def repo_root() -> Path:
    return Path(__file__).resolve().parents[1]


def read_text(path: Path) -> str:
    return path.read_text(encoding="utf-8")


def extract_macro_body(source: str, path: Path) -> str:
    marker = "impl_syscall_nums_and_dispatch_fn!"
    marker_index = source.find(marker)
    if marker_index == -1:
        raise ValueError(f"{path}: missing {marker} macro invocation")

    open_index = source.find("{", marker_index)
    if open_index == -1:
        raise ValueError(f"{path}: malformed {marker} macro invocation")

    depth = 0
    for index in range(open_index, len(source)):
        char = source[index]
        if char == "{":
            depth += 1
        elif char == "}":
            depth -= 1
            if depth == 0:
                return source[open_index + 1 : index]

    raise ValueError(f"{path}: unterminated {marker} macro invocation")


def extract_macro_entries(path: Path) -> list[SyscallEntry]:
    body = extract_macro_body(read_text(path), path)
    entries: list[SyscallEntry] = []
    for line_number, line in enumerate(body.splitlines(), start=1):
        stripped = line.strip()
        if not stripped or stripped.startswith("//"):
            continue

        match = ENTRY_RE.match(line)
        if match is None:
            raise ValueError(f"{path}: unrecognized syscall table line {line_number}: {line!r}")

        entries.append(
            SyscallEntry(
                name=match.group(1),
                number=int(match.group(2)),
                handler=match.group(3).strip(),
            )
        )
    return entries


def extract_framevm_special_entries(path: Path, names: set[str]) -> list[SyscallEntry]:
    entries: list[SyscallEntry] = []
    for line in read_text(path).splitlines():
        match = STANDALONE_CONST_RE.match(line)
        if match is None or match.group(1) not in names:
            continue
        entries.append(
            SyscallEntry(
                name=match.group(1),
                number=int(match.group(2)),
                handler="special service exit dispatch",
            )
        )
    return entries


def validate_unique(entries: list[SyscallEntry], label: str) -> None:
    names: dict[str, int] = {}
    numbers: dict[int, str] = {}
    for entry in entries:
        if entry.name in names:
            raise ValueError(f"duplicate {label} syscall name {entry.name}")
        names[entry.name] = entry.number
        if entry.number in numbers:
            raise ValueError(
                f"duplicate {label} syscall number {entry.number}: "
                f"{numbers[entry.number]} and {entry.name}"
            )
        numbers[entry.number] = entry.name


def validate_framevm_against_kernel(kernel_entries: list[SyscallEntry], framevm_entries: list[SyscallEntry]) -> None:
    kernel_numbers = {entry.name: entry.number for entry in kernel_entries}
    for entry in framevm_entries:
        kernel_number = kernel_numbers.get(entry.name)
        if kernel_number is None:
            if entry.name in FRAMEVM_ONLY_UNSUPPORTED_SYSCALLS:
                continue
            raise ValueError(f"FrameVM syscall {entry.name} is not present in kernel x86 syscall table")
        if kernel_number != entry.number:
            raise ValueError(
                f"FrameVM syscall {entry.name} uses number {entry.number}, "
                f"but kernel x86 syscall table uses {kernel_number}"
            )

def rust_string(value: str) -> str:
    return '"' + value.replace('\\', '\\\\').replace('"', '\\"') + '"'


def render_entries(entries: list[SyscallEntry]) -> list[str]:
    lines: list[str] = []
    for entry in sorted(entries, key=lambda item: item.number):
        lines.append(
            f"    SyscallMetadata {{ name: {rust_string(entry.name)}, "
            f"number: {entry.number}, handler: {rust_string(entry.handler)} }},"
        )
    return lines


def render_metadata(kernel_entries: list[SyscallEntry], framevm_entries: list[SyscallEntry]) -> str:
    lines = [
        GENERATED_HEADER.rstrip("\n"),
        "",
        "#![expect(dead_code, reason = \"Generated syscall metadata is verified by the boundary check.\")]",
        "",
        "pub(super) struct SyscallMetadata {",
        "    pub name: &'static str,",
        "    pub number: u64,",
        "    pub handler: &'static str,",
        "}",
        "",
        "pub(super) const KERNEL_X86_SYSCALLS: &[SyscallMetadata] = &[",
    ]
    lines.extend(render_entries(kernel_entries))
    lines.extend(
        [
            "];",
            "",
            "pub(super) const FRAMEVM_X86_SYSCALLS: &[SyscallMetadata] = &[",
        ]
    )
    lines.extend(render_entries(framevm_entries))
    lines.extend(
        [
            "];",
        ]
    )
    return "\n".join(lines) + "\n"


def metadata_inputs(root: Path) -> tuple[Path, Path, Path]:
    return (
        root / "kernel/src/syscall/arch/x86.rs",
        root / "services/aster-framevm/src/syscall/arch/x86.rs",
        root / "services/aster-framevm/src/syscall/arch/x86_generated.rs",
    )


def generated_metadata(root: Path) -> str:
    kernel_path, framevm_path, _ = metadata_inputs(root)
    kernel_entries = extract_macro_entries(kernel_path)
    framevm_entries = extract_macro_entries(framevm_path)
    framevm_entries.extend(
        extract_framevm_special_entries(framevm_path, names={"SYS_EXIT", "SYS_EXIT_GROUP"})
    )

    validate_unique(kernel_entries, "kernel x86")
    validate_unique(framevm_entries, "FrameVM x86")
    validate_framevm_against_kernel(kernel_entries, framevm_entries)

    return render_metadata(kernel_entries, framevm_entries)


def check_metadata(root: Path) -> int:
    _, _, output_path = metadata_inputs(root)
    if not output_path.exists():
        print(f"error: generated syscall metadata is missing: {output_path}", file=sys.stderr)
        return 1

    current = read_text(output_path)
    if not current.startswith(GENERATED_HEADER):
        print(f"error: generated syscall metadata header is missing or stale: {output_path}", file=sys.stderr)
        return 1

    expected = generated_metadata(root)
    if current == expected:
        return 0

    diff = difflib.unified_diff(
        current.splitlines(keepends=True),
        expected.splitlines(keepends=True),
        fromfile=str(output_path),
        tofile=f"{output_path} (regenerated)",
    )
    sys.stderr.writelines(diff)
    print(
        "error: generated syscall metadata is stale; run "
        "`python3 tools/generate_framevm_syscall_metadata.py`",
        file=sys.stderr,
    )
    return 1


def write_metadata(root: Path) -> None:
    _, _, output_path = metadata_inputs(root)
    output_path.write_text(generated_metadata(root), encoding="utf-8")


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--check",
        action="store_true",
        help="fail if generated syscall metadata is missing, stale, or has a stale header",
    )
    return parser.parse_args()


def main() -> int:
    args = parse_args()
    root = repo_root()
    try:
        if args.check:
            return check_metadata(root)
        write_metadata(root)
    except ValueError as error:
        print(f"error: {error}", file=sys.stderr)
        return 1
    return 0


if __name__ == "__main__":
    raise SystemExit(main())