# SPDX-License-Identifier: MPL-2.0

# FrameVsock Throughput Benchmark (Asterinas Host side)
# These programs run on Asterinas Host to communicate with FrameVM Guest.

include ../test_common.mk

EXTRA_C_FLAGS :=
